const allItems = [
    { id: 1, name: "Apple MacBook Pro", category: "Electronics", price: 1800 },
    { id: 2, name: "Dell XPS 15", category: "Electronics", price: 1600 },
    { id: 3, name: "Sony WH-1000XM5 Headphones", category: "Electronics", price: 350 },
    { id: 4, name: "Logitech MX Master 3S Mouse", category: "Accessories", price: 100 },
    { id: 5, name: "Samsung Odyssey G9 Monitor", category: "Electronics", price: 1200 },
    { id: 6, name: "Ergonomic Office Chair", category: "Furniture", price: 400 },
    { id: 7, name: "Standing Desk", category: "Furniture", price: 600 },
    { id: 8, name: "Mechanical Keyboard", category: "Accessories", price: 150 },
    { id: 9, name: "External SSD 1TB", category: "Storage", price: 120 },
    { id: 10, name: "Gaming PC (Custom Build)", category: "Electronics", price: 2500 },
    { id: 11, name: "Noise-Cancelling Earbuds", category: "Electronics", price: 200 },
    { id: 12, name: "Webcam Full HD", category: "Accessories", price: 70 },
    { id: 13, name: "Wireless Router WiFi 6", category: "Networking", price: 180 },
    { id: 14, name: "Smart Thermostat", category: "Smart Home", price: 200 },
    { id: 15, name: "Robot Vacuum Cleaner", category: "Smart Home", price: 450 },
    { id: 16, name: "Coffee Maker Espresso", category: "Home Appliances", price: 300 },
    { id: 17, name: "Air Fryer", category: "Home Appliances", price: 100 },
    { id: 18, name: "Fitness Tracker", category: "Wearables", price: 90 },
    { id: 19, name: "Smartwatch", category: "Wearables", price: 250 },
    { id: 20, name: "VR Headset", category: "Gaming", price: 400 },
    { id: 21, name: "Gaming Console PS5", category: "Gaming", price: 500 },
    { id: 22, name: "Gaming Console Xbox Series X", category: "Gaming", price: 500 },
    { id: 23, name: "4K Smart TV 65-inch", category: "Electronics", price: 900 },
    { id: 24, name: "Soundbar with Subwoofer", category: "Electronics", price: 250 },
    { id: 25, name: "Digital Camera Mirrorless", category: "Photography", price: 1200 }
]
export default allItems;